[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
on_chain_voting = "8s4gonpXfvVTcjMF1p7GGqiS1a5BVVvuGhzvarwNRgiC"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
