[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
on_chain_voting = "DVPoVewzorwzAtuZ8Dgu5xzuBMLdLy7rXtHhNR8oeFr3"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
